### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by az-z** [tdack/turbo-pascal-syntax#9]
Hate to open the issue, but i think this awesome theme stopped working correctly on the latest Atom (1.16.0, Fedora 25 x64)
Do you mind to take a look please?

**Comment by tdack** [comment]
I have updated the [base.less](https://github.com/tdack/turbo-pascal-syntax/blob/master/styles/base.less) style to what the latest version of Atom is using and it appears to be working once again.

**Comment by az-z** [comment]
thank you!
